name: Train Model (MLflow Project)

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MLflow
        run: |
          pip install mlflow

      - name: Install Dependencies (optional jika pakai conda.yaml MLflow)
        run: |
          cd MLProject
          pip install -r requirements.txt || true

      - name: Run MLflow Project
        run: |
          mlflow run MLProject/ --env-manager local